# Generated by Django 4.1.5 on 2023-02-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globaladmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='last_parsed',
            field=models.CharField(default='02/02/2023, 08:20:11', max_length=150),
        ),
    ]
