# Generated by Django 4.1.5 on 2023-02-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globaladmin', '0003_parsingstatus_alter_cases_last_parsed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='last_parsed',
            field=models.CharField(default='02/02/2023, 08:45:20', max_length=150),
        ),
        migrations.AlterField(
            model_name='parsingstatus',
            name='last_parsed',
            field=models.CharField(default='02/02/2023, 08:45:20', max_length=100),
        ),
    ]
