# Generated by Django 4.1.5 on 2023-02-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='MyUsers',
        ),
    ]
