# Generated by Django 4.1.5 on 2023-02-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_users_myusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='role',
            field=models.CharField(default='Пользователь', max_length=100),
        ),
    ]
